### ISSUE TITLE
nfs::mount ensure: mounted does not work

### ISSUE THREAD

**Issue by ipoppo** [ghoneycutt/puppet-module-nfs#45]
Specify `ensure: mounted` will cause the following log

```
Notice: /Stage[main]/Nfs/Types::Mount[package-mount]/Mount[/mnt/package]/ensure: ensure changed 'unmounted' to 'mounted'
Error: /Stage[main]/Nfs/Types::Mount[package-mount]/Mount[/mnt/package]: Could not evaluate: Execution of '/bin/mount /mnt/package' returned 32: mount.nfs: an incorrect mount option was specified
```

Specify `ensure: present` does not generate log and create /mnt/package but device not mounted (as expected)

```yaml
# sample common.yaml
nfs::mounts:
  package-mount:
    name:    "%{hiera('package::mount')}"
    device:  "%{hiera('package::hostname')}:%{hiera('package::export')}"
    ensure:  mounted
    options: rw,sync,no_root_squash
    fstype:  nfs
```
